server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-lab-dekra-lab-dekra.e4ff.pro-eu-west-1.openshiftapps.com/eureka/,http://eureka-replica-lab-dekra-lab-dekra.e4ff.pro-eu-west-1.openshiftapps.com/eureka/
