server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761
      #defaultZone: http://eureka-server-lab-dekra-lab-dekra.e4ff.pro-eu-west-1.openshiftapps.com/eureka/,http://eureka-replica-lab-dekra-lab-dekra.e4ff.pro-eu-west-1.openshiftapps.com/eureka/
